#!/usr/bin/env python
import json
import sys
import os
import asyncio
import time

# Fix imports when running directly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from crewai.flow.flow import Flow, start, listen, router, or_
from crewai.flow.persistence import persist

# Import the SystemState from the model folder
from master_flow.model.system_state import SystemState

# Import the crews
# from master_flow.crews.macro_planning_crew.macro_crew import MacroPlanningCrew
# from master_flow.crews.micro_learning_crew.micro_crew import MicroLearningCrew
from master_flow.crews.macro_planning_crew.macro_generator import generate_macro_blueprint_single_shot
from master_flow.crews.micro_learning_crew.micro_generator import generate_micro_theory_single_shot

@persist()
class MasterFlow(Flow[SystemState]):
    
    # @start()
    # def execute_macro_planning(self):
    #     print(f"--- MACRO PLANNING CREW ACTIVATED ---")
    #     start_time = time.time()
        
    #     inputs = {
    #         "topic": self.state.topic,
    #         "experience": self.state.experience,
    #         "goal": self.state.goal,
    #         "constraints": self.state.constraints or "None specified."
    #     }
        
    #     # Kickoff the Crew. Runs Architect only now.
    #     result = MacroPlanningCrew().crew().kickoff(inputs=inputs)
        
    #     import os
    #     debug_info = {
    #         "pydantic_output": result.pydantic.model_dump() if hasattr(result, "pydantic") and result.pydantic else None,
    #         "json_dict_output": result.json_dict if hasattr(result, "json_dict") else None,
    #         "raw_output": result.raw if hasattr(result, "raw") else None,
    #         "tasks_output": [
    #             {
    #                 "raw": t.raw if hasattr(t, "raw") else None,
    #                 "json_dict": t.json_dict if hasattr(t, "json_dict") else None,
    #                 "pydantic": t.pydantic.model_dump() if hasattr(t, "pydantic") and t.pydantic else None
    #             } for t in (result.tasks_output if hasattr(result, "tasks_output") else [])
    #         ]
    #     }
        
    #     # Save trace to help debug empty arrays
    #     debug_path = os.path.join(os.path.dirname(__file__), "../../api/temp_macro_crew_debug.json")
    #     try:
    #         with open(debug_path, "w", encoding="utf-8") as f:
    #             json.dump(debug_info, f, indent=2, default=str)
    #     except Exception as e:
    #         print(f"Warning: Could not write debug info to {debug_path}: {e}")

    #     # Extract the Architect's blueprint directly with robust fallbacks
    #     try:
    #         if result.pydantic:
    #             self.state.blueprint = result.pydantic.model_dump()
    #         elif result.json_dict:
    #             self.state.blueprint = result.json_dict
    #         else:
    #             raw_text = getattr(result, "raw", "")
    #             if raw_text:
    #                 import re
    #                 match = re.search(r'\{.*\}', raw_text, re.DOTALL)
    #                 if match:
    #                     self.state.blueprint = json.loads(match.group(0))
    #                 else:
    #                     self.state.blueprint = {"nodes": []}
    #             else:
    #                 self.state.blueprint = {"nodes": []}
    #     except Exception as e:
    #         print(f"Warning: Could not extract architect blueprint. {e}")
    #         self.state.blueprint = {"nodes": []}
            
    #     # Log final blueprint state assigned to the master flow
    #     final_blueprint_path = os.path.join(os.path.dirname(__file__), "../../api/temp_macro_blueprint_final.json")
    #     try:
    #         with open(final_blueprint_path, "w", encoding="utf-8") as f:
    #             json.dump(self.state.blueprint, f, indent=2)
    #     except Exception as e:
    #         print(f"Warning: Could not write final blueprint to {final_blueprint_path}: {e}")

    #     print("--- BLUEPRINT GENERATED BY ARCHITECT ---")
    #     self.state.macro_duration = time.time() - start_time
    #     print(f"\n⏳ [DURATION TRACKER] Macro Phase completed in: {self.state.macro_duration:.2f} seconds\n")
    @start()
    async def execute_macro_planning(self):
        print(f"--- MACRO PLANNING SINGLE-SHOT ACTIVATED ---")
        start_time = time.time()
        
        try:
            # Call the lightning-fast Single-Shot function
            blueprint_dict = await generate_macro_blueprint_single_shot(
                topic=self.state.topic,
                experience=self.state.experience,
                goal=self.state.goal,
                constraints=self.state.constraints or "None specified."
            )
            self.state.blueprint = blueprint_dict
            
        except Exception as e:
            print(f"Warning: Could not extract architect blueprint. {e}")
            self.state.blueprint = {"nodes": []}
            
        # Log final blueprint state assigned to the master flow
        final_blueprint_path = os.path.join(os.path.dirname(__file__), "../../api/temp_macro_blueprint_final.json")
        try:
            with open(final_blueprint_path, "w", encoding="utf-8") as f:
                json.dump(self.state.blueprint, f, indent=2)
        except Exception as e:
            print(f"Warning: Could not write final blueprint to {final_blueprint_path}: {e}")

        print("--- BLUEPRINT GENERATED BY ARCHITECT ---")
        self.state.macro_duration = time.time() - start_time
        print(f"\n⏳ [DURATION TRACKER] Macro Phase completed in: {self.state.macro_duration:.2f} seconds\n")

    @listen(execute_macro_planning)
    async def process_all_nodes(self):
        """Process all nodes concurrently using async kickoff."""
        print(f"--- MICRO PLANNING PHASE ACTIVATED ---")
        start_time = time.time()
        blueprint_data = self.state.blueprint # This is the dict saved from Macro Crew
        pending_nodes = blueprint_data.get("nodes", [])

        semaphore = asyncio.Semaphore(8)

        # async def process_single_node(node):
        #     print(f"--- GENERATING CONTENT FOR (ASYNC): {node['title']} ---")
        #     inputs = {
        #         "macro_title": node['title'],
        #         "node_id": node['node_id'],
        #         "micro_topics_list": ", ".join(node['suggested_micro_topics']),
        #         "experience": self.state.experience,
        #         "goal": self.state.goal
        #     }
        #     try:
        #         result = await MicroLearningCrew().crew().akickoff(inputs=inputs)
        #         if result.pydantic:
        #             return result.pydantic.model_dump()
        #         elif result.json_dict:
        #             return result.json_dict
        #         else:
        #             print(f"Warning: No valid pydantic output from Micro Crew for {node['title']}")
        #             return None
        #     except Exception as e:
        #         print(f"Error processing node {node['title']}: {e}")
        #         return None
        async def process_single_node(node):
            print(f"--- GENERATING CONTENT FOR (ASYNC SCoT): {node['title']} ---")
            
            try:
                # Call our lightning-fast single-shot controller instead of CrewAI
                pydantic_result = await generate_micro_theory_single_shot(
                    node_id=node['node_id'],
                    module_title=node['title'],
                    suggested_micro_topics=node['suggested_micro_topics'],
                    experience=self.state.experience,  
                    goal=self.state.goal           
                )
                
                # Convert the Pydantic object back to a standard dictionary for the UI
                return pydantic_result.model_dump()
                
            except Exception as e:
                print(f"Error processing node {node['title']}: {e}")
                return None

        results = await asyncio.gather(*[process_single_node(n) for n in pending_nodes])
        self.state.completed_modules = [r for r in results if r is not None]
        self.state.micro_duration = time.time() - start_time
        print(f"\n⏳ [DURATION TRACKER] Micro Phase completed in: {self.state.micro_duration:.2f} seconds\n")

    @listen(process_all_nodes)
    def finish_course(self):
        reply = "Your complete, personalized micro-learning course is ready!"
        self.state.chat_history.append({"role": "assistant", "content": reply})
        return {
            "status": "complete", 
            "reply": reply, 
            "blueprint": self.state.blueprint,
            "course_content": self.state.completed_modules
        }

def kickoff():
    master_flow = MasterFlow()
    master_flow.kickoff()

def plot():
    master_flow = MasterFlow()
    master_flow.plot()

if __name__ == "__main__":
    kickoff()
